### PR TITLE
Feature/Projects Overview

### PR DESCRIPTION
**Pull request by fmgoncalves**

### CODE REVIEW

**Comment by dpnova** [comment]
Looking good mate!

**Comment by dpnova** [comment]
@ejjick can you have a look at some of the bootstrap things?

**Comment by dpnova** [comment]
cc here @ejjick

**Comment by fmgoncalves** [comment]
Ok, I think this is good enough to drop [WIP] and review.
Keep in mind this page `tse/projects` isn't linked from anywhere since I don't know what flow we want including this.
Also, the cards only link to ssot because the links on the prototype don't exist at this stage.

@dpnova
I "littered" the Project model with validations and tests so adding projects with all their new fields could be as safe as possible from `/admin`.

@ejjick
For some situations the project cards are misaligned or weird-looking (when a project lacks a logo, or has a very long name or description). Can you help me out with the relevant bootstrap classes and such to make it look pleasant and consistent?

**Comment by dpnova** [comment]
I'll pull this and have a play tomorrow before accepting.

**Comment by ejjick** [comment]
I've pushed some fixes for when project cards are misaligned or weird-looking (when a project lacks a logo, or has a very long name or description).

It's hard coded ugly css for now. We'll observe what's consistent among the projects and adapt the design accordingly.

The description field for now is capped at 3 lines (~100 characters). We can add a "View description" button or add a "Read more" when it's too long.

**Pull request merged**
